# Generated by Django 5.0.4 on 2024-04-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0003_staff_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='others', max_length=10),
        ),
    ]
